package br.com.des.livraria.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Emprestimo generated by hbm2java
 */
@Entity
@Table(name = "emprestimo", schema = "testedsl")
public class Emprestimo implements java.io.Serializable {

	private long idemprestimo;
	private Livro livro;
	private Pessoa pessoa;
	private Date dataemprestimo;
	private Date datahoradevolucao;

	public Emprestimo() {
	}

	public Emprestimo(long idemprestimo, Livro livro, Pessoa pessoa, Date dataemprestimo) {
		this.idemprestimo = idemprestimo;
		this.livro = livro;
		this.pessoa = pessoa;
		this.dataemprestimo = dataemprestimo;
	}

	public Emprestimo(long idemprestimo, Livro livro, Pessoa pessoa, Date dataemprestimo, Date datahoradevolucao) {
		this.idemprestimo = idemprestimo;
		this.livro = livro;
		this.pessoa = pessoa;
		this.dataemprestimo = dataemprestimo;
		this.datahoradevolucao = datahoradevolucao;
	}

	@Id
	@Column(name = "idemprestimo", unique = true, nullable = false)
	public long getIdemprestimo() {
		return this.idemprestimo;
	}

	public void setIdemprestimo(long idemprestimo) {
		this.idemprestimo = idemprestimo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idlivro", nullable = false)
	public Livro getLivro() {
		return this.livro;
	}

	public void setLivro(Livro livro) {
		this.livro = livro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpessoa", nullable = false)
	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataemprestimo", nullable = false, length = 13)
	public Date getDataemprestimo() {
		return this.dataemprestimo;
	}

	public void setDataemprestimo(Date dataemprestimo) {
		this.dataemprestimo = dataemprestimo;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "datahoradevolucao", length = 15)
	public Date getDatahoradevolucao() {
		return this.datahoradevolucao;
	}

	public void setDatahoradevolucao(Date datahoradevolucao) {
		this.datahoradevolucao = datahoradevolucao;
	}

}
