package br.com.des.livraria.model;

// Generated Jun 27, 2015 3:31:07 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name = "pessoa", schema = "testedsl")
public class Pessoa implements java.io.Serializable {

	private long idpessoa;
	private String nome;
	private Date datanascimento;
	private String cpf;
	private Set<Emprestimo> emprestimos = new HashSet<Emprestimo>(0);

	public Pessoa() {
	}

	public Pessoa(long idpessoa, String nome) {
		this.idpessoa = idpessoa;
		this.nome = nome;
	}

	public Pessoa(long idpessoa, String nome, Date datanascimento, String cpf, Set<Emprestimo> emprestimos) {
		this.idpessoa = idpessoa;
		this.nome = nome;
		this.datanascimento = datanascimento;
		this.cpf = cpf;
		this.emprestimos = emprestimos;
	}

	@Id
	@Column(name = "idpessoa", unique = true, nullable = false)
	public long getIdpessoa() {
		return this.idpessoa;
	}

	public void setIdpessoa(long idpessoa) {
		this.idpessoa = idpessoa;
	}

	@Column(name = "nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datanascimento", length = 13)
	public Date getDatanascimento() {
		return this.datanascimento;
	}

	public void setDatanascimento(Date datanascimento) {
		this.datanascimento = datanascimento;
	}

	@Column(name = "cpf", length = 14)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	public Set<Emprestimo> getEmprestimos() {
		return this.emprestimos;
	}

	public void setEmprestimos(Set<Emprestimo> emprestimos) {
		this.emprestimos = emprestimos;
	}

}
